// Story content — Meu Marido Dormia Com Minha Melhor Amiga (Capítulo 1)
export const STORY_TITLE = "Meu Marido Dormia Com Minha Melhor Amiga";
export const STORY_SUBTITLE = "Drama · Traição · Reviravolta";
export const STORY_AUTHOR = "Prendix Originals";
export const STORY_READ_TIME = "18 min de leitura";
export const STORY_CATEGORY = "Drama";
export const STORY_TAGS = ["Drama", "Traição", "Suspense", "Reviravolta"];
export const STORY_HOOK = "Dez anos de casamento. Uma mensagem anônima. Uma pulseira de bebê com o meu nome — mas o filho não é meu.";

export const STORY_PARAGRAPHS: string[] = [
  "No dia em que completei dez anos de casada, descobri que meu marido tinha um filho recém-nascido.",
  "Até aí, já seria suficiente para destruir qualquer mulher.",
  "Mas a parte mais doentia era outra.",
  "Na pulseira do bebê, o nome da mãe era o meu.",
  "Meu nome.",
  "Bianca Almeida Costa.",
  "O nome que eu assinei no cartório quando me casei.",
  "O nome que estava na fachada pequena da minha loja de decoração.",
  "O nome que aparecia na agenda da escola da minha filha.",
  "O nome que eu carreguei por trinta e quatro anos sem imaginar que um dia alguém usaria para transformar minha vida em uma armadilha.",
  "Aquela sexta-feira começou bonita demais.",
  "Hoje eu desconfio de dias bonitos demais.",
  "Acordei cedo. Fiz café. Arrumei a mesa da cozinha com pão francês, mamão cortado e o bolo simples que Nina, minha filha de oito anos, insistiu em preparar na noite anterior.",
  "Ela dizia que bolo de aniversário de casamento precisava ser feito por alguém que acreditasse no casal.",
  "Eu acreditei por dez anos.",
  "Nina entrou na cozinha usando o uniforme da escola e uma tiara torta no cabelo.",
  "NINA: Mãe, hoje você e o papai fazem dez anos de casados ou dez anos de namoro?",
  "BIANCA: De casados.",
  "NINA: E de namoro?",
  "BIANCA: Treze.",
  "Ela abriu a boca, espantada.",
  "NINA: Nossa. Isso é quase uma pessoa adolescente.",
  "Sorri.",
  "BIANCA: É. Nosso casamento já está entrando na fase difícil.",
  "Mateus apareceu atrás dela, já vestido para trabalhar. Camisa azul-clara, calça social, cabelo ainda úmido do banho. Ele beijou a cabeça de Nina e depois beijou minha testa.",
  "Ele sempre beijava minha testa.",
  "Durante anos, achei aquilo delicado.",
  "Depois entendi que alguns homens beijam a testa da esposa com a mesma calma com que trancam uma gaveta.",
  "MATEUS: Bom dia, minhas meninas.",
  "NINA: Pai, hoje tem discurso?",
  "MATEUS: Claro que tem.",
  "NINA: Grande?",
  "MATEUS: Do tamanho do amor que sinto pela sua mãe.",
  "Nina fez uma careta.",
  "NINA: Então vai demorar. Vou levar massinha para brincar.",
  "Eu ri.",
  "Mateus também.",
  "Era isso que tornava tudo pior depois.",
  "A naturalidade.",
  "A mesa posta.",
  "O café quente.",
  "A criança rindo.",
  "O marido mentindo com a boca cheia de pão.",
  "Mateus era professor de biologia em um colégio particular. Era inteligente, paciente, educado. Daqueles homens que as pessoas elogiavam até quando ele não estava presente.",
  "Minha mãe, antes de morrer, dizia que eu tinha dado sorte.",
  "Minha sogra dizia que eu tinha segurado um homem raro.",
  "Minhas amigas diziam que homem como Mateus não se encontrava mais.",
  "E Laura, minha melhor amiga, dizia sempre a mesma frase:",
  "LAURA: Se um dia você largar esse homem, eu te interno.",
  "Laura ria quando dizia isso.",
  "Eu ria junto.",
  "A gente ri de certas frases porque ainda não sabe que elas são avisos.",
  "Naquela manhã, Mateus saiu para trabalhar às sete e quarenta.",
  "Antes de passar pela porta, voltou e me abraçou pela cintura.",
  "MATEUS: Hoje não faz jantar. Eu resolvo tudo.",
  "BIANCA: Você?",
  "MATEUS: Eu. Confia em mim.",
  "Confia em mim.",
  "Essa frase devia vir com sirene.",
  "Passei o dia na loja tentando fingir que não estava ansiosa. Vendemos duas luminárias, um jogo de almofadas e um espelho grande para uma cliente que queria “dar cara de mulher rica” à sala do apartamento alugado.",
  "Às quinze e vinte, Laura apareceu.",
  "Ela entrou sem bater, como sempre.",
  "Laura era o tipo de pessoa que parecia pertencer a todos os lugares. Bonita sem esforço. Cabelo castanho sempre arrumado. Perfume doce. Riso fácil. Ela trabalhava com eventos e sabia transformar qualquer mesa simples em cenário de revista.",
  "Trazia nas mãos uma sacola com velas, guardanapos e duas garrafas de vinho.",
  "LAURA: Trouxe reforço para a noite dos pombinhos.",
  "BIANCA: Eu falei para não gastar.",
  "LAURA: E eu fingi que ouvi.",
  "Ela colocou tudo sobre o balcão e olhou para mim com atenção.",
  "LAURA: Você está feliz?",
  "A pergunta veio estranha. Simples demais. Direta demais.",
  "BIANCA: Estou. Por quê?",
  "LAURA: Nada. Dez anos é muita coisa.",
  "BIANCA: É.",
  "LAURA: Você ainda ama ele?",
  "Olhei para ela.",
  "BIANCA: Que pergunta é essa?",
  "Laura deu de ombros.",
  "LAURA: Pergunta de amiga.",
  "BIANCA: Amo.",
  "Ela sorriu, mas o sorriso não chegou inteiro.",
  "LAURA: Então aproveita hoje.",
  "Na hora, não entendi.",
  "Hoje, quando lembro, essa frase tem cheiro de fósforo riscado.",
  "Às dezoito, fechei a loja. Passei no mercado, comprei gelo, morangos e refrigerante para Nina. Cheguei em casa e encontrei a sala decorada.",
  "Mateus tinha pendurado fotos nossas na parede.",
  "Eu e ele na praia.",
  "Eu grávida da Nina.",
  "Nós três no primeiro dia de aula dela.",
  "Nossa mudança para aquela casa.",
  "Minha mãe no último Natal em família.",
  "O casamento inteiro estava ali, preso em barbantes com luzes pequenas.",
  "Parecia bonito.",
  "Parecia verdadeiro.",
  "Mateus saiu da cozinha usando avental.",
  "MATEUS: Surpresa.",
  "BIANCA: Você fez isso?",
  "MATEUS: Com ajuda da Nina.",
  "Nina apareceu atrás dele com as mãos sujas de brigadeiro.",
  "NINA: Eu fui a chefe.",
  "MATEUS: Foi mesmo.",
  "Ele se aproximou e me entregou um buquê de lírios brancos.",
  "Eu odiava lírios.",
  "Ele sabia disso.",
  "Ou deveria saber.",
  "Lírios tinham cheiro de hospital. De missa. De coisa terminando de forma limpa demais.",
  "Mesmo assim, peguei o buquê.",
  "BIANCA: Obrigada.",
  "MATEUS: Não gostou?",
  "BIANCA: Gostei.",
  "A primeira mentira daquela noite foi minha.",
  "Os convidados começaram a chegar depois das dezenove.",
  "Minha sogra, Célia, veio com um pudim.",
  "Meu cunhado trouxe cerveja.",
  "Minha vizinha apareceu com uma travessa de maionese.",
  "Laura chegou por último.",
  "Vestido vinho.",
  "Cabelo preso.",
  "Brincos dourados.",
  "Bonita demais para uma festa simples de aniversário de casamento de outra pessoa.",
  "Ela me abraçou forte.",
  "Forte demais.",
  "LAURA: Dez anos, amiga.",
  "BIANCA: Dez anos.",
  "LAURA: Você aguentou bastante.",
  "Ela falou no meu ouvido, rindo baixo.",
  "Mas não parecia brincadeira.",
  "Antes que eu respondesse, Mateus apareceu atrás de mim.",
  "MATEUS: Laura.",
  "LAURA: Mateus.",
  "Foi rápido.",
  "Rápido demais para qualquer pessoa perceber.",
  "Mas eu percebi.",
  "O olhar dos dois se encontrou e fugiu.",
  "Na época, eu não tinha ainda a prova.",
  "Mas o corpo sabe antes da cabeça.",
  "A festa seguiu.",
  "Risadas.",
  "Taças.",
  "Comida.",
  "Nina fez uma apresentação no meio da sala, rodando com o vestido amarelo. Todo mundo bateu palma. Mateus filmou.",
  "Eu estava na cozinha quando o celular dele vibrou sobre a mesa.",
  "Ele tinha deixado o aparelho ali enquanto ajudava minha sogra a tirar o pudim da forma.",
  "Eu não mexia no celular do meu marido.",
  "Tinha orgulho disso.",
  "Dizia para todo mundo que confiança era a base de um casamento.",
  "Hoje eu sei que base também pode ser buraco.",
  "A tela acendeu.",
  "Não havia nome salvo.",
  "Só uma mensagem.",
  "MENSAGEM: Não deixe ele brindar antes de você olhar o bolso interno do paletó.",
  "Meu corpo ficou parado.",
  "Minha mão estava segurando uma travessa de arroz. Por um segundo, achei que fosse derrubar tudo.",
  "Olhei para a sala.",
  "Mateus ria com meu cunhado.",
  "Laura mexia no próprio celular.",
  "Ninguém olhava para mim.",
  "A mensagem sumiu da tela.",
  "O celular apagou.",
  "Fiquei ali, ouvindo a geladeira, os talheres, as vozes, minha filha rindo.",
  "Eu podia ignorar.",
  "Podia fingir que não vi.",
  "Podia convencer a mim mesma de que era engano, brincadeira, golpe, mensagem errada.",
  "Mas existe um tipo de medo que não manda você correr.",
  "Ele manda você investigar.",
  "Subi para o quarto.",
  "O paletó azul-marinho de Mateus estava pendurado no cabide, exatamente onde ele deixava roupas que pretendia usar depois. Era o paletó do nosso casamento civil. Ele dizia que dava sorte.",
  "Fechei a porta devagar.",
  "A casa parecia longe.",
  "Coloquei a mão no bolso externo.",
  "Nada.",
  "No outro.",
  "Nada.",
  "Respirei fundo e enfiei os dedos no bolso interno.",
  "Encontrei um papel dobrado.",
  "Abri.",
  "Era um comprovante.",
  "Hotel Jardim das Orquídeas. Suíte 304. Entrada: 14h12. Saída: 17h48.",
  "A data era daquela terça-feira.",
  "Três dias antes.",
  "Na terça, às quatorze horas, Mateus tinha me mandado uma foto da mesa dele no colégio.",
  "MATEUS, NA MENSAGEM ANTIGA: Dia puxado. Corrigindo prova até agora. Saudade de você.",
  "Lembro que respondi com um coração.",
  "Um coração.",
  "O símbolo mais burro quando a pessoa do outro lado está pisando nele.",
  "Dobrei o comprovante de novo.",
  "Minha mão voltou ao bolso.",
  "Havia outra coisa.",
  "Plástico.",
  "Puxei.",
  "Era uma pulseira de maternidade.",
  "Daquelas pulseiras pequenas colocadas em recém-nascidos.",
  "Li devagar.",
  "Uma vez.",
  "Duas.",
  "Três.",
  "O mundo ficou sem barulho.",
  "Mãe: Bianca Almeida Costa. Bebê: masculino. Nascimento: 16h03. Maternidade Santa Cecília. Quarto: 304.",
  "Senti uma pressão no peito.",
  "Não era dor.",
  "Era como se alguém tivesse colocado uma mão por dentro de mim e apertado tudo.",
  "Eu não estava grávida.",
  "Eu não tinha parido.",
  "Eu não tinha estado em maternidade nenhuma.",
  "Mas havia um bebê.",
  "E ele estava no meu nome.",
  "A porta do quarto abriu.",
  "Mateus entrou.",
  "Eu enfiei a pulseira de volta no bolso por puro instinto.",
  "Ele me encontrou de pé, perto do guarda-roupa.",
  "MATEUS: Amor?",
  "Meu rosto devia estar branco.",
  "MATEUS: Está tudo bem?",
  "Não sei como consegui responder.",
  "BIANCA: Está.",
  "MATEUS: O que você está fazendo aqui?",
  "BIANCA: Vim pegar meu brinco.",
  "Ele apontou para a penteadeira.",
  "MATEUS: O dourado está ali.",
  "O dourado.",
  "Ele lembrava do brinco.",
  "Lembrava da minha agenda.",
  "Lembrava do remédio de alergia da Nina.",
  "Lembrava como minha mãe gostava do café.",
  "Mas não lembrava que eu não tinha parido um menino naquela tarde.",
  "Ou lembrava muito bem.",
  "Mateus se aproximou.",
  "MATEUS: Você está tremendo.",
  "BIANCA: Estou com frio.",
  "MATEUS: Quer que eu pegue um casaco?",
  "BIANCA: Não.",
  "Ele me olhou por um tempo.",
  "Aquele olhar me estudava.",
  "Não era preocupação.",
  "Era cálculo.",
  "MATEUS: Bia, aconteceu alguma coisa?",
  "Quase perguntei.",
  "Quase joguei o paletó na cara dele.",
  "Quase gritei o nome de Laura.",
  "Mas alguma coisa dentro de mim, talvez a parte mais inteligente da minha dor, mandou eu ficar quieta.",
  "BIANCA: Só estou cansada.",
  "Ele sorriu.",
  "MATEUS: Depois do brinde você descansa.",
  "Voltei para a sala.",
  "A festa continuava.",
  "Era cruel como o mundo não parava.",
  "Minha sogra cortava o pudim.",
  "Nina mostrava um desenho para a vizinha.",
  "Laura segurava uma taça de vinho e conversava com meu cunhado.",
  "Olhei para a barriga dela.",
  "Plana.",
  "Magrela.",
  "Perfeita.",
  "Não parecia uma mulher que tinha acabado de dar à luz.",
  "Mas o comprovante dizia hotel.",
  "A pulseira dizia maternidade.",
  "O quarto era o mesmo.",
  "Sentei no sofá.",
  "Minha cabeça começou a juntar peças sem permissão.",
  "Hotel Jardim das Orquídeas.",
  "Maternidade Santa Cecília.",
  "Quarto 304.",
  "Lírios.",
  "Orquídeas.",
  "Flores por toda parte.",
  "Flores cobrindo cheiro de coisa morta.",
  "Às vinte e duas, Célia bateu na taça com uma colher.",
  "CÉLIA: Discurso! Dez anos merecem discurso!",
  "Todo mundo concordou.",
  "Mateus levantou.",
  "Eu fiquei sentada.",
  "Ele pegou minha mão e me puxou para perto.",
  "O toque dele me deu nojo.",
  "Mas fiquei.",
  "Minha filha estava olhando.",
  "MATEUS: Eu preparei poucas palavras.",
  "Laura abaixou os olhos.",
  "Mateus respirou fundo.",
  "MATEUS: Quando conheci a Bianca, eu não sabia o que era casa. Eu achava que vida era trabalho, conta paga e fim de semana. Ela me ensinou que família é construção diária.",
  "Algumas pessoas suspiraram.",
  "Eu olhei para a mão dele segurando a minha.",
  "Aquela mesma mão tinha segurado outro bebê horas antes?",
  "MATEUS: Bianca me deu a Nina. Me deu amor. Me deu estabilidade. Me deu tudo que um homem pode desejar.",
  "Laura apertou a taça.",
  "MATEUS: E eu posso dizer, diante de todos vocês, que nunca escondi nada dela que pudesse destruir nosso casamento.",
  "A taça de Laura caiu.",
  "O vidro estourou no chão.",
  "O vinho se espalhou pelo piso claro.",
  "Vermelho.",
  "Grosso.",
  "Quase bonito.",
  "Laura levou a mão à boca.",
  "LAURA: Meu Deus. Desculpa. Que desastrada.",
  "Mateus parou de falar.",
  "Só por um segundo.",
  "Mas eu vi.",
  "Vi o olhar dele nela.",
  "Vi o medo.",
  "Vi a raiva.",
  "Vi tudo o que eu não tinha visto em dez anos.",
  "Meu celular vibrou.",
  "Número desconhecido.",
  "MENSAGEM: Ele está mentindo agora. Vai à Maternidade Santa Cecília. Quarto 304. Antes que apaguem seu nome.",
  "Anexada à mensagem havia uma foto.",
  "Mateus em um corredor de hospital.",
  "Ele segurava um bebê enrolado em manta azul.",
  "Ao lado dele, uma mulher de costas.",
  "Vestido vinho.",
  "Cabelo preso.",
  "Laura.",
  "Meu estômago afundou.",
  "A sala girou um pouco.",
  "Nina puxou minha manga.",
  "NINA: Mãe, você está chorando?",
  "Passei a mão no rosto.",
  "Não havia lágrima.",
  "BIANCA: Não, meu amor. Caiu uma coisa no meu olho.",
  "Mateus ainda me olhava.",
  "MATEUS: Bia?",
  "Sorri.",
  "Foi o sorriso mais difícil da minha vida.",
  "BIANCA: Acabou o gelo.",
  "Minha sogra apontou para a cozinha.",
  "CÉLIA: Tem no freezer.",
  "BIANCA: Não é suficiente. Eu vou comprar.",
  "Mateus deu um passo.",
  "MATEUS: Eu vou com você.",
  "BIANCA: Não precisa.",
  "MATEUS: Bianca.",
  "Ele quase nunca me chamava de Bianca.",
  "Só quando queria controlar a situação.",
  "BIANCA: Eu volto rápido.",
  "Laura estava parada ao lado do vinho quebrado.",
  "Ela me olhava como se já soubesse para onde eu ia.",
  "E talvez soubesse mesmo.",
  "Peguei a bolsa, a chave do carro e saí.",
  "Na garagem, minhas pernas quase falharam.",
  "Entrei no carro e tranquei as portas.",
  "Digitei o endereço da maternidade.",
  "O aplicativo dizia nove minutos.",
  "Nove minutos é pouco.",
  "Nove minutos também é tempo suficiente para uma mulher morrer por dentro e continuar dirigindo.",
  "No caminho, lembrei do filho que perdi cinco anos antes.",
  "Eu estava grávida de onze semanas.",
  "Mateus chorou comigo no banheiro.",
  "Laura dormiu na minha casa durante três noites.",
  "Ela segurou meu cabelo quando eu vomitei de tanto chorar.",
  "Foi Laura quem disse:",
  "LAURA: Um dia essa dor vai virar outra coisa.",
  "Na época, achei que ela falava de cura.",
  "Talvez falasse de plano.",
  "Cheguei à maternidade às vinte e duas e trinta e oito.",
  "Estacionei longe da entrada.",
  "Entrei tentando parecer calma.",
  "A recepcionista sorriu.",
  "RECEPCIONISTA: Boa noite.",
  "BIANCA: Boa noite. Quarto 304.",
  "Ela digitou no computador.",
  "RECEPCIONISTA: Nome da paciente?",
  "A pergunta me atravessou.",
  "BIANCA: Bianca Almeida Costa.",
  "Ela levantou os olhos para mim.",
  "RECEPCIONISTA: A senhora é a paciente?",
  "Meu coração bateu uma vez, pesado.",
  "BIANCA: Sou.",
  "A recepcionista olhou a tela de novo.",
  "RECEPCIONISTA: Consta que a senhora está em repouso no quarto.",
  "Senti o chão sair.",
  "BIANCA: Eu precisei descer.",
  "RECEPCIONISTA: Certo. Terceiro andar, corredor à direita.",
  "Ela não pediu documento.",
  "Não pediu nada.",
  "Meu nome era chave.",
  "Subi de elevador sozinha.",
  "No espelho, vi uma mulher de vestido azul-marinho, cabelo preso, batom apagado e olhos que pareciam ter envelhecido dez anos em uma noite.",
  "Terceiro andar.",
  "Corredor à direita.",
  "Quarto 304.",
  "A porta estava entreaberta.",
  "Ouvi uma voz.",
  "A voz de Mateus.",
  "MATEUS: Ela não vai descobrir hoje.",
  "Depois, Laura.",
  "LAURA: Você prometeu isso ontem. Prometeu semana passada. Prometeu há meses.",
  "Meses.",
  "A palavra entrou em mim como faca sem pressa.",
  "MATEUS: Fala baixo.",
  "LAURA: Eu não aguento mais ficar escondida.",
  "MATEUS: Mais dois dias.",
  "LAURA: Dois dias para quê?",
  "MATEUS: Para o registro sair. Depois disso, ela não vai ter escolha.",
  "Não vai ter escolha.",
  "Empurrei a porta só um pouco.",
  "Vi Mateus sentado numa poltrona.",
  "Ele segurava o bebê.",
  "Laura estava de pé ao lado da cama, ainda com o vestido vinho da festa.",
  "Não tinha barriga.",
  "Não tinha cara de puérpera.",
  "Não parecia ter acabado de parir.",
  "Mas havia uma mala dela no canto.",
  "Havia flores.",
  "Havia uma bolsa de bebê.",
  "Havia uma vida inteira montada naquele quarto.",
  "No bercinho, uma placa.",
  "Nome: Miguel Almeida Costa. Mãe: Bianca Almeida Costa. Pai: Mateus Ribeiro Costa.",
  "Miguel.",
  "O nome que eu escolhi para o bebê que perdi.",
  "Mateus beijou a testa do recém-nascido.",
  "MATEUS: Meu filho.",
  "Laura passou a mão pelo rosto.",
  "LAURA: E eu? O que eu sou nessa história?",
  "Mateus não respondeu.",
  "Laura virou o rosto.",
  "Ela me viu na porta.",
  "Por um segundo, nenhuma de nós respirou.",
  "Então ela disse, baixo:",
  "LAURA: Você veio.",
  "Não foi surpresa.",
  "Foi confirmação.",
  "E aí eu entendi.",
  "A mensagem anônima não era só aviso.",
  "Era convite.",
  "Eles queriam que eu visse.",
  "Queriam me colocar diante do bebê, da traição, do meu nome roubado.",
  "Queriam que eu explodisse.",
  "Queriam que eu parecesse louca.",
  "Mateus levantou os olhos e me viu.",
  "O rosto dele não mostrou culpa.",
  "Mostrou irritação.",
  "Como se eu tivesse chegado cedo demais a uma reunião marcada.",
  "MATEUS: Bianca.",
  "Laura começou a chorar.",
  "O bebê mexeu os braços dentro da manta azul.",
  "Ninguém disse nada por alguns segundos.",
  "Então Mateus falou a frase que terminou de abrir o buraco debaixo dos meus pés.",
  "MATEUS: Antes de você fazer escândalo, precisa entender uma coisa.",
  "Ele segurou o bebê mais perto do peito.",
  "MATEUS: Esse filho também é seu."
];
