// Story content — edit freely.
export const STORY_TITLE = "Meu Desamor Perfeito";
export const STORY_SUBTITLE = "Romance · Drama · Desejo";
export const STORY_AUTHOR = "Prendix Originals";
export const STORY_READ_TIME = "12 min de leitura";
export const STORY_CATEGORY = "Drama";
export const STORY_TAGS = ["Romance", "Drama", "Traição", "Recomeço"];
export const STORY_HOOK = "Cinco anos de casamento. Zero noites juntos. E o nome que ele sussurrou no banheiro não era o dela.";

export const STORY_PARAGRAPHS: string[] = [
  "Do banheiro vinha o som constante da água caindo.",
  "Era Adrián Vargas, tomando banho.",
  "Três da madrugada.",
  "Ele tinha acabado de chegar.",
  "Olivia Muñoz estava parada diante da porta do banheiro, com o coração apertado. Precisava falar com ele. Havia algo importante preso na garganta, algo que vinha ensaiando há dias, mas que ainda não sabia como dizer.",
  "Estava nervosa.",
  "Não sabia se Adrián aceitaria.",
  "Não sabia se ele entenderia.",
  "E, enquanto tentava encontrar a melhor forma de começar aquela conversa, ouviu um som estranho vindo de dentro.",
  "Olivia prendeu a respiração.",
  "Aproximou o ouvido.",
  "Então entendeu.",
  "Ele estava… se tocando.",
  "Os gemidos abafados e a respiração pesada vieram um atrás do outro, como golpes secos contra o peito dela.",
  "O mundo pareceu afundar.",
  "Uma dor espessa subiu por sua garganta, sufocante, cruel, impossível de engolir.",
  "Aquele dia era o aniversário de casamento deles.",
  "Cinco anos casada com Adrián.",
  "Cinco anos dividindo a mesma casa.",
  "Cinco anos dormindo na mesma cama.",
  "E, em todo esse tempo, eles nunca tinham tido intimidade.",
  "Nunca.",
  "Ele preferia se satisfazer sozinho a encostar nela?",
  "A respiração de Olivia começou a falhar.",
  "Então, do outro lado da porta, Adrián murmurou baixinho, com extremo cuidado, como se aquele nome fosse sagrado:",
  "— Pau…",
  "Aquele nome foi o golpe final.",
  "O último pedaço de esperança dentro dela se partiu em silêncio.",
  "Olivia levou a mão à boca com força para não chorar. Virou-se para fugir dali, mas, no primeiro passo, tropeçou. Bateu no lavatório e caiu no chão.",
  "— Olivia? —A voz de Adrián veio de dentro do banheiro, ainda rouca e ofegante. Dava para perceber que ele tentava se controlar, mas a respiração continuava pesada.",
  "— Eu… eu só queria usar o banheiro. Não sabia que você estava tomando banho… —mentiu, atrapalhada, agarrando-se ao lavatório para tentar levantar.",
  "Quanto mais se apressava, mais humilhada se sentia.",
  "Havia água no chão e no móvel. Ela mal conseguiu ficar de pé quando Adrián saiu do banheiro.",
  "Ele vestia um roupão branco, colocado às pressas, embora o cinto estivesse amarrado com força demais.",
  "— Você caiu? Deixa eu te ajudar —disse ele, tentando pegá-la no colo.",
  "As lágrimas de dor já ardiam nos olhos dela.",
  "Mesmo assim, Olivia afastou a mão dele.",
  "Humilhada, mas firme.",
  "— Não precisa. Eu consigo sozinha.",
  "No segundo seguinte, escorregou outra vez e quase caiu de novo.",
  "Ainda assim, mancando, saiu dali depressa e se refugiou no quarto.",
  "Fugir.",
  "Essa era a palavra certa.",
  "Durante os cinco anos em que esteve casada com Adrián, Olivia não tinha feito outra coisa além de fugir.",
  "Fugir do mundo lá fora.",
  "Fugir dos olhares curiosos.",
  "Fugir da pena dos outros.",
  "E fugir, principalmente, da compaixão silenciosa do próprio marido.",
  "Como a esposa de Adrián Vargas podia ser manca?",
  "Como uma mulher como ela poderia estar à altura de um homem tão brilhante, tão bonito, tão bem-sucedido?",
  "E pensar que, antes, suas pernas eram perfeitas.",
  "Adrián a seguiu até o quarto.",
  "A voz dele veio suave, preocupada.",
  "— Você se machucou? Deixa eu ver.",
  "— Não. Estou bem.",
  "Olivia se enrolou nos lençóis, escondendo junto com o corpo toda a vergonha que sentia.",
  "— Tem certeza? —ele perguntou, sinceramente preocupado.",
  "— Tenho.",
  "Ela virou de costas para ele e assentiu com força.",
  "— Então vamos dormir? Você não queria ir ao banheiro?",
  "— Já passou. Melhor você dormir, tá? —murmurou.",
  "— Está bem. Ah, hoje é nosso aniversário. Comprei um presente para você. Abre amanhã e vê se gosta.",
  "— Tá.",
  "O presente estava na mesa de cabeceira.",
  "Ela já tinha visto.",
  "Nem precisava abrir para saber o que era.",
  "Todos os anos, a mesma caixa.",
  "O mesmo tamanho.",
  "O mesmo relógio.",
  "Na gaveta dela, contando aniversários e datas comemorativas, já havia nove relógios praticamente iguais.",
  "Aquele seria o décimo.",
  "A conversa morreu ali.",
  "A luz foi apagada.",
  "Adrián deitou.",
  "O cheiro úmido do sabonete ainda vinha dele, mas Olivia mal sentiu o colchão afundar. Naquela cama king size, ela dormia de um lado e ele no extremo oposto. Entre os dois, caberiam mais três pessoas.",
  "Nenhum deles mencionou “Pau”.",
  "Muito menos o que ele estava fazendo no banheiro.",
  "Era como se nada tivesse acontecido.",
  "Olivia permaneceu deitada, rígida, sentindo os olhos queimarem.",
  "Pau.",
  "Paulina Castillo.",
  "Colega de faculdade dele.",
  "Seu primeiro amor.",
  "Sua deusa inalcançável.",
  "Depois da formatura, Paulina foi para o exterior e os dois terminaram. Adrián entrou em depressão e passou a beber todos os dias.",
  "Olivia e ele tinham sido colegas no ensino médio.",
  "Ela admitia: gostava dele em segredo desde aquela época.",
  "Adrián era o garoto mais bonito da escola, o aluno perfeito, sério, distante.",
  "Ela estudava artes.",
  "Também era bonita, sim, mas havia muitas garotas bonitas.",
  "Numa escola onde notas eram tudo, os alunos de artes quase não tinham destaque. Alguns, inclusive, os olhavam com preconceito.",
  "Por isso, o amor de Olivia foi silencioso.",
  "Platônico.",
  "Solitário.",
  "Ela jamais imaginou que um dia poderia se aproximar dele.",
  "Até que, depois de se formar na academia de dança e voltar para casa durante as férias, encontrou Adrián completamente destruído.",
  "Naquela noite, ele também estava bêbado.",
  "Caminhava cambaleando pela rua.",
  "Atravessou sem olhar para o semáforo.",
  "Um carro vinha em alta velocidade, sem tempo para frear.",
  "Foi Olivia, que o seguia preocupada, quem o empurrou para salvá-lo.",
  "Mas o carro atingiu ela.",
  "Ela era bailarina.",
  "Já tinha garantido a entrada no mestrado.",
  "Mas, por causa daquele acidente, ficou manca.",
  "Nunca mais pôde dançar.",
  "Depois disso, Adrián parou de beber e se casou com ela.",
  "Sempre culpado.",
  "Sempre grato.",
  "Sempre gentil.",
  "Sempre distante.",
  "Enchia Olivia de presentes.",
  "Dava todo o dinheiro que ela quisesse.",
  "Mas não a amava.",
  "Ela acreditou que o tempo aqueceria aquela relação.",
  "Acreditou que o passado seria apagado.",
  "Jamais imaginou que, cinco anos depois, “Pau” ainda estivesse tão cravada na mente dele.",
  "A ponto de ele gemer o nome dela enquanto se dava prazer.",
  "No fim, Olivia tinha sido ingênua demais.",
  "Não dormiu a noite inteira.",
  "Leu mais de cem vezes o e-mail no celular.",
  "Era a carta de aceitação de uma universidade no exterior para o mestrado.",
  "Esse era o assunto que queria tratar com Adrián naquela noite.",
  "Queria estudar fora.",
  "Queria saber se ele concordaria.",
  "Mas agora estava claro.",
  "Ela não precisava pedir permissão.",
  "Cinco anos de casamento.",
  "Incontáveis noites virando de um lado para o outro.",
  "A partir daquele momento, Olivia podia iniciar sua contagem regressiva.",
  "Quando amanheceu, fingiu continuar dormindo.",
  "Ouviu Adrián conversando com Rosa, a empregada.",
  "— Hoje tenho um jantar de negócios. Diga à senhora que não me espere e que durma cedo.",
  "Depois de dar as instruções, ele voltou ao quarto e olhou para ela.",
  "Olivia continuava coberta pelos lençóis.",
  "Mas as lágrimas já tinham encharcado o travesseiro.",
  "Normalmente, antes de Adrián sair para o escritório, ela deixava a roupa dele separada, combinada, pronta para vestir.",
  "Dessa vez, não fez isso.",
  "Ele foi sozinho ao closet, se trocou e saiu para a Graph Corporation.",
  "Só então Olivia abriu os olhos.",
  "Eles estavam inchados e doloridos.",
  "O alarme do celular tocou.",
  "Era o horário que ela havia definido para estudar o idioma.",
  "Desde que se casara, por causa da perna, Olivia passava noventa por cento do tempo dentro de casa. Quase não saía.",
  "Precisava dividir o dia em blocos e encontrar alguma coisa para ocupar cada parte dele.",
  "Qualquer coisa que impedisse o tempo de esmagá-la.",
  "Pegou o celular, desligou o alarme e começou a navegar sem rumo por vários aplicativos.",
  "Sua cabeça estava um caos.",
  "Não prestava atenção em nada.",
  "Até que um vídeo apareceu no Instagram.",
  "A pessoa na tela era familiar demais.",
  "Olivia olhou o nome da conta:",
  "@soypaucastillo.",
  "Maldito algoritmo.",
  "A publicação era da noite anterior.",
  "Olivia abriu o vídeo.",
  "Uma música animada começou a tocar.",
  "Logo depois, alguém gritou:",
  "— Um, dois, três! Bem-vinda de volta, Pau! Saúde!",
  "Aquela voz…",
  "Era Adrián.",
  "Ele tinha quebrado a própria regra.",
  "Bebeu álcool.",
  "Dava para perceber pela voz.",
  "Parecia até um pouco bêbado.",
  "Mas Adrián era capaz de gritar assim?",
  "A imagem que Olivia tinha dele era completamente diferente.",
  "No ensino médio, Adrián era o aluno brilhante e inalcançável. Mantinha a mesma expressão séria resolvendo problemas de matemática ou jogando na quadra, ignorando as garotas apaixonadas que corriam para oferecer água.",
  "Mais tarde, como marido, tornou-se um homem educado, mas de emoções tão estáveis que pareciam inexistentes.",
  "Nunca ria.",
  "Nunca se irritava.",
  "Sempre mantinha aquela postura indiferente, tão distante que, nas raras vezes em que seus dedos se tocavam, Olivia sentia que a temperatura dele era baixa, quase sem vida.",
  "Mas no vídeo, a câmera percorreu os rostos dos presentes.",
  "E lá estava ele.",
  "Bochechas coradas.",
  "Olhos brilhantes.",
  "Taça erguida.",
  "Rindo abertamente para a câmera.",
  "— Bem-vinda para casa, Pau.",
  "Então ele sabia rir.",
  "Ele também tinha paixão.",
  "Ele também sabia tratar uma mulher com carinho.",
  "Só não ria com Olivia.",
  "Só não sentia paixão por Olivia.",
  "Muito menos a chamava por um apelido carinhoso.",
  "— Senhora, já vai se levantar? —A voz de Rosa soou no corredor.",
  "A vida de Olivia era metódica, disciplinada.",
  "Ao notar que não havia barulho no quarto, Rosa se preocupou que ela precisasse de ajuda. Afinal, o problema em sua perna era uma realidade impossível de ignorar.",
  "Olivia deixou o celular de lado.",
  "— Sim. Já estou indo.",
  "A própria voz a surpreendeu.",
  "Rouca.",
  "À beira do choro.",
  "No café da manhã, Rosa havia preparado frutas picadas e pão doce.",
  "Olivia mal conseguiu comer dois pedaços antes de se sentir cheia.",
  "— Senhora, o que gostaria para o almoço e o jantar? —perguntou Rosa, colocando um copo de leite perto da mão dela.",
  "— Qualquer coisa, mas…",
  "Ela quase respondeu como sempre:",
  "“Prepare o que o senhor mais gosta.”",
  "Mas engoliu as palavras a tempo.",
  "Rosa, acostumada com aquela rotina diária, entendeu a intenção e se apressou em explicar:",
  "— O senhor Vargas avisou que não virá almoçar hoje. Tem um compromisso de negócios.",
  "Olivia assentiu.",
  "Claro que ele não viria.",
  "Ela já sabia.",
  "Tinha acabado de ver no Instagram.",
  "Paulina publicara um calendário detalhado de quem a levaria para almoçar durante a semana e quais pratos estava com vontade de comer.",
  "A legenda dizia:",
  "“O carinho da época da escola é o mais sincero. Sou uma menininha mimada pelos meus garotos!”",
  "A rotina diurna de Olivia consistia em estudar idioma por duas horas, seguida de várias horas de teoria da arte.",
  "Se não encontrasse algo para ocupar a mente, como suportaria as horas mortas?",
  "Dedicaria sua vida inteira a esperar um homem voltar para casa?",
  "Ela já tinha feito isso.",
  "E o sabor da espera era amargo demais.",
  "Mas, naquele dia, sua agenda era diferente.",
  "A carta de aceitação que havia recebido provavelmente era da última rodada de admissões da universidade. Ela precisava confirmar sua vaga.",
  "Por isso, a primeira coisa que fez foi transferir o valor da matrícula.",
  "Quando a notificação de cobrança apareceu na tela do celular, Olivia soltou o ar devagar.",
  "Estava um dia mais perto de deixar Adrián.",
  "Ao entardecer, trocou de roupa, pronta para sair.",
  "Rosa a observou com curiosidade.",
  "— Senhora, aonde vai?",
  "Sem a companhia de Adrián, Olivia quase nunca saía de casa.",
  "— Uma colega da faculdade veio à cidade para uma apresentação. Ela me convidou para assistir —mentiu.",
  "Na verdade, planejava se hospedar num hotel perto do local da prova que faria na manhã seguinte.",
  "A prova era cedo demais.",
  "Ela tinha medo de o trânsito atrasá-la se saísse de casa.",
  "Meses antes, já havia feito o exame, mas não alcançara a pontuação ideal. Ainda assim, como o prazo das inscrições de pós-graduação estava terminando, enviou os documentos com aquela nota.",
  "Jamais esperou ser aceita.",
  "Por precaução, havia agendado essa segunda tentativa.",
  "Felizmente, a universidade permitia atualizar o certificado de idioma depois.",
  "— Mas… —Rosa olhou para a perna dela—, quer que eu vá junto?",
  "— Não precisa. É uma reunião de meninas. Seria estranho levar outra pessoa —respondeu Olivia, mantendo a expressão neutra.",
  "— Então vou avisar o senhor, para ele ficar tranquilo —insistiu a empregada, com medo de que algo acontecesse sob sua responsabilidade.",
  "— Não. Deixe ele trabalhar em paz. Não o incomode. Quando eu terminar de ver minha amiga, ligo para ele me buscar —disse Olivia, pegando a bolsa e saindo.",
  "Pensando na dificuldade dela para caminhar, Adrián tinha comprado aquele apartamento de luxo num andar com acesso direto.",
  "Olivia só precisou pegar o elevador.",
  "Quando saiu para a rua e sentiu a luz do sol, abaixou a cabeça por instinto.",
  "Encolheu os ombros.",
  "Ajustou o chapéu.",
  "Levantou a gola do casaco.",
  "Desde que ficara manca, a Olivia que brilhava confiante nos palcos havia desaparecido.",
  "A “Olivia manca” não tinha coragem de enfrentar os olhares do mundo.",
  "Rosa sempre dizia que era melhor esperar o senhor Vargas acompanhá-la.",
  "Adrián também repetia que, sem ele ao lado, era melhor ela ficar em casa.",
  "Mas nenhum dos dois entendia a verdade.",
  "O que mais assustava Olivia era sair com Adrián.",
  "Tinha mais medo disso do que de sair sozinha.",
  "Porque nos olhos de cada pessoa que os via juntos, ela conseguia ler a mesma pergunta cruel:",
  "“Por que um homem tão perfeito tem uma esposa manca?”",
  "Olivia chamou um carro por aplicativo e seguiu em direção à região do hotel.",
  "Durante o trajeto, olhava em silêncio a cidade pela janela, quando de repente reconheceu um veículo estacionado à beira da rua.",
  "Era o carro de Adrián.",
  "— Espere. Pare aqui, por favor —pediu ao motorista.",
  "O carro do marido estava diante de um restaurante exclusivo.",
  "No dia anterior, um dos amigos de infância havia convidado Paulina.",
  "Agora era a vez de Adrián, exatamente como ela tinha postado.",
  "Olivia desceu do carro como se uma força desconhecida a empurrasse.",
  "Entrou no restaurante e foi até a recepção.",
  "— Vim ver o senhor Vargas. Já estão me esperando —disse, fornecendo os últimos dígitos do celular de Adrián para confirmação.",
  "O recepcionista a guiou até a porta de uma sala privada.",
  "— É aqui.",
  "— Obrigada.",
  "Olivia agradeceu, mas, no fundo, não sabia o que estava fazendo ali.",
  "Em casa, sentira impulso e raiva.",
  "Agora, parada diante da porta, a coragem de empurrá-la parecia ter evaporado.",
  "Do lado de dentro, risadas e conversas animadas ecoavam.",
  "— Hoje não posso chegar tarde. E nada de álcool. Ontem cheguei bêbado e minha velha virou uma fera.",
  "Aquela voz era de um dos amigos de infância de Adrián.",
  "— Sério? Cadê aquele que dizia que os amigos vinham primeiro? Agora virou mandado pela esposa? Ainda bem que o meu Adri é amigo de verdade.",
  "Era Paulina.",
  "A voz dela era doce, pegajosa, suave.",
  "Então era esse o tipo de personalidade dela.",
  "E era esse o tipo de garota de quem Adrián gostava.",
  "Que pena.",
  "Olivia não era assim.",
  "E, mesmo que quisesse, jamais conseguiria fingir ser.",
  "O amigo de Adrián continuou:",
  "— Como você compara? Adrián é outro nível. Olivia não teria coragem de dizer meia palavra para ele.",
  "— Falando nisso… —Paulina voltou a falar—, Adri, ouvi dizer que sua esposa é manca. É verdade? O que aconteceu com ela?",
  "Ninguém respondeu.",
  "Mas o coração de Olivia se contraiu dolorosamente.",
  "Os amigos de Adrián aproveitaram o silêncio para opinar.",
  "— Adri, dá até raiva. Olha para você: rico, bonito, bem-sucedido. Poderia ter a mulher que quisesse. Por que diabos se casou com uma aleijada?",
  "— Sério, você é o melhor de nós. Mas com Olivia… seja numa reunião, num jantar de negócios ou numa coletiva, você não pode levar ela para lugar nenhum. Não sente que saiu perdendo?",
  "Então era isso.",
  "Adrián sempre dizia que ela não precisava se envolver nos assuntos dele.",
  "Que bastava ficar tranquila em casa, esperando enquanto ele trazia dinheiro.",
  "A própria família de Olivia o idolatrava por isso.",
  "Todos diziam que ela tinha uma sorte enorme.",
  "Mas a realidade era outra.",
  "Ele sentia vergonha de mostrá-la em público.",
  "De dentro da sala, ouviu-se a risada amarga de Adrián.",
  "— Ela me ajudou naquela época. Devo muito a ela. É gratidão.",
  "— Se devia alguma coisa, já deu dinheiro suficiente! Com isso, estavam quites!",
  "— Exato. Devia ter pagado bem e pronto. Que necessidade havia de sacrificar sua felicidade para sempre?",
  "— Pensa bem. Se você enchesse a casa de cruzes e velas, pelo menos teria bênçãos. Mas de que adianta ter aquela mulher em casa?",
  "— Sim, o que ela pode fazer por você? Não serve para eventos sociais. E em casa você deve até ter medo de ela derrubar café em cima de você se tentar servir. Ela serve café assim… assim, andando torta?",
  "Uma gargalhada geral explodiu na sala.",
  "A risada de Paulina se destacava.",
  "Zombeteira.",
  "Presa à porta, Olivia sentiu o sangue subir à cabeça.",
  "A raiva e a humilhação a fizeram perder a razão por um instante.",
  "Ela empurrou a porta com força.",
  "A sala se abriu.",
  "Lá dentro, o ambiente era um caos de risadas.",
  "Um dos amigos, Beto, segurava uma taça e atravessava a sala exagerando uma marcha manca, arrastando um pé e torcendo o corpo, enquanto imitava uma voz fina.",
  "— Toma… Ai, vou cair! Me segura!",
  "Olivia fixou os olhos em Adrián.",
  "Esperava, desesperadamente, que o marido, o homem que ela amara com toda a alma, tivesse alguma reação.",
  "Que a defendesse.",
  "Mas aquela imitação ridícula fez os presentes caírem ainda mais na gargalhada.",
  "Paulina, sentada ao lado de Adrián, riu tanto que acabou se apoiando no ombro dele.",
  "E Adrián, para surpresa de Olivia, não disse uma única palavra.",
  "Beto virou-se ainda sorrindo.",
  "— É assim que ela…",
  "A frase morreu antes do fim quando viu Olivia parada na porta.",
  "O sorriso congelou.",
  "— O… Olivia…",
  "Todos se viraram para a entrada.",
  "Ficaram paralisados.",
  "Paulina se afastou do ombro de Adrián e, com uma naturalidade assustadora, sorriu.",
  "— Ah, você deve ser a famosa esposa do Adri, né? Entra. Eu sou muito amiga dele.",
  "Olivia passou os olhos por todos no salão privado.",
  "Sentiu um vazio doloroso.",
  "Adrián se levantou e caminhou até ela.",
  "— O que está fazendo aqui? Eles só estavam brincando. Não leve para o lado pessoal.",
  "Olivia o encarou.",
  "Ele parecia um estranho.",
  "Mais distante do que nunca.",
  "Então era isso.",
  "Quando os outros zombavam da esposa dele, ele escolhia ficar do lado dos que riam?",
  "— Sim, é… desculpa. Era brincadeira. Não fica brava —disse Beto, largando a taça na mesa.",
  "— Olivia! —Adrián chegou diante dela e tentou envolvê-la com o braço.",
  "Mas ela se lembrou de Paulina encostada naquele ombro, rindo.",
  "Lembrou-se da mão dele se tocando no banheiro.",
  "Lembrou-se daquele “Pau” sussurrado.",
  "E sentiu que aquela mão estava imunda.",
  "Ela se afastou.",
  "Adrián olhou para a própria mão vazia, surpreso, e suspirou.",
  "— Peço desculpas por eles, tá? Não fica brava, por favor. Quando voltarmos para casa, compro um presente para você. O que quiser. É só dizer.",
  "Paulina lançou a Beto um olhar de reprovação brincalhona.",
  "— Você deixou a esposa do Adri chateada. Peça desculpas direito! Acha que todo mundo é como eu, meio bruta, que aguenta as grosserias de vocês? Vocês brincam pesado demais com qualquer pessoa!",
  "Olivia sorriu com amargura.",
  "Que santinha.",
  "Mas era óbvio que aquele grupo de homens não percebia a manipulação.",
  "Pelo contrário.",
  "Engoliam tudo.",
  "Beto, sentindo-se injustiçado pelo puxão de orelha, resmungou:",
  "— Mas eu já pedi desculpa! Eu não sabia que ela ia aparecer. Era só brincadeira.",
  "— Uma brincadeira… —disse Olivia, a voz tremendo, juntando toda a coragem que ainda tinha— só é brincadeira quando a pessoa de quem vocês riem também acha graça.",
  "Ela era manca.",
  "Não merecia Adrián.",
  "Essa ideia havia se agarrado a ela como uma maldição durante os últimos cinco anos.",
  "Qualquer olhar de dúvida ou desprezo fazia Olivia querer recuar, esconder-se em seu ninho como um animal ferido e ficar muito tempo ali, lambendo as próprias feridas em silêncio.",
  "Beto ouviu e resmungou:",
  "— Eu já pedi desculpa!",
  "— Eu… não aceito suas desculpas… —Olivia tremia cada vez mais.",
  "Era a primeira vez que enfrentava uma humilhação assim.",
  "— E então o que você quer que eu faça? —Beto reclamou.",
  "Olivia também não sabia.",
  "Só sabia que rejeitava aquilo.",
  "Rejeitava a situação.",
  "Rejeitava os amigos do marido zombando dela.",
  "E, acima de tudo, rejeitava que o marido estivesse do lado deles.",
  "— Chega. Calem a boca —ordenou Adrián, colocando-se entre Olivia e Beto.",
  "Ele era o líder daquele grupo.",
  "Desde que se formaram, guiava todos.",
  "Graças ao instinto comercial e à capacidade de execução de Adrián, a Graph Corporation havia alcançado o sucesso que tinha.",
  "Por isso, quando ele falava, ninguém ousava dizer mais nada.",
  "Adrián olhou para Olivia com aquela calma de sempre.",
  "Um olhar completamente diferente daquele brilho que ela vira no vídeo com Paulina.",
  "— Eles são meus amigos há anos. Não tiveram má intenção. Só estavam brincando. Faça isso por mim: perdoe eles. Quer que eu peça ao motorista para te levar?",
  "— Amiga… —Paulina fez um bico e se levantou ao lado de Adrián—, se você está mesmo chateada, fique brava comigo, mas não pare de falar com o Adri. Eles se reuniram hoje porque eu voltei… Adri, fala para sua esposa ficar e jantar com a gente. Eu brindo com ela para ela me perdoar.",
  "Que hipocrisia descarada.",
  "— Desculpa. —Olivia olhou para Adrián.",
  "Se Paulina se atrevia a falar assim, era porque ele permitia.",
  "Olivia engoliu a amargura que subia pela garganta.",
  "— Eu não bebo. Muito menos quando a taça vem servida com tanta falsidade.",
  "Paulina fez cara de quem estava prestes a chorar e olhou para Adrián.",
  "— Ela está me insultando? Eu… —então assumiu uma expressão de quem segurava as lágrimas com coragem— Não tem problema. Ela me entendeu mal. Não importa que diga essas coisas. Não brigue com ela…",
  "O rosto de Adrián ficou sério.",
  "— Pau teve a melhor das intenções. Por que você precisa ser tão amarga e grosseira?",
  "A melhor das intenções?",
  "Só um idiota acreditaria nisso.",
  "Adrián era idiota?",
  "Não.",
  "Não era.",
  "Entre o certo e o errado, ele simplesmente escolheu ser parcial.",
  "Para onde o coração dele se inclinava, ali também ficava a razão.",
  "Olivia olhou para os dois diante dela.",
  "Depois para as pessoas atrás deles.",
  "Sentiu que havia um abismo impossível de atravessar entre ela e aquele grupo.",
  "Eles eram um bloco unido.",
  "Uma frente sólida.",
  "Ela não passava de uma intrusa no mundo deles.",
  "Não.",
  "Pior.",
  "Ela nunca tinha conseguido entrar naquele mundo.",
  "Mesmo orbitando ao redor, ainda sobrava.",
  "Segurando a vontade de chorar, soltou um riso quase imperceptível, virou-se e caminhou para a saída.",
  "Atrás dela, ouviu Paulina dizer:",
  "— Sua esposa…",
  "— Não tem problema. Ela é muito compreensiva. Depois eu chego em casa e agrado ela. Continuem, não se preocupem —disse Adrián, embora tenha olhado discretamente para as costas de Olivia e enviado uma mensagem ao motorista para levá-la.",
  "Olivia queria caminhar com dignidade.",
  "Com passos firmes.",
  "Mas não conseguia.",
  "Quanto mais se alterava, mais a perna falhava.",
  "Naquele momento, fugindo de forma tão desajeitada e desesperada, será que parecia exatamente como Beto a imitava?",
  "Provavelmente, assim que ela saísse, todos voltariam a gargalhar.",
  "Olivia limpou as lágrimas com raiva e acelerou o passo.",
  "Mancando ainda mais.",
  "Quando o motorista de Adrián saiu correndo atrás dela, Olivia já não estava diante do restaurante.",
  "O motorista voltou para informar Adrián.",
  "Adrián franziu levemente a testa e ligou para ela.",
  "Olivia não atendeu.",
  "Cortou a chamada.",
  "Ele ligou outra vez.",
  "Mas o celular já estava desligado.",
  "Beto, ainda irritado, aproveitou para falar:",
  "— Esse temperamento da sua esposa é culpa sua. Você mima demais. Com o dinheiro que tem e essa sua imagem, qualquer mulher te colocaria num altar dentro de casa. E ela fica fazendo drama. Você tem paciência demais.",
  "Adrián permaneceu em silêncio.",
  "Os outros apoiaram Beto.",
  "— Ele tem razão. Você se sacrificou muito por ela e por essa casa. Trabalha feito louco, e ela não é capaz nem de te compreender nem de ser atenciosa. Faz escândalo por uma besteira dessas. Vale a pena?",
  "— Exato. Você se casar com ela já foi um milagre na vida dela. Se não fosse você, uma manca como ela, quem ia querer? Teria que se casar com outro deficiente.",
  "Paulina, sempre atenta às reações, interveio no momento perfeito.",
  "— Adri, por favor, não fique chateado só porque eles dizem que sua mulher não está à sua altura. Todos falam pelo seu bem. Pense em quantos anos de amizade vocês têm… Mesmo que tenham passado um pouco do limite, escute e pronto. Não leve tão a sério.",
  "— Não estou chateado —respondeu Adrián, guardando o celular—. Tanto faz. Ela não vai a lugar nenhum. Vamos continuar.",
  "Afinal, nos últimos cinco anos, além da própria casa, Olivia nunca tinha ido a lugar algum.",
  "Ela não tinha para onde ir.",
  "Beto olhou para Paulina e murmurou:",
  "— Nossa Pau sim tem classe. Se vocês dois não tivessem terminado naquela época…",
  "— O que você está dizendo? —Paulina o interrompeu, lançando-lhe um olhar de aviso— Você passou a noite inteira sem se controlar, só falando besteira! O Adri já é casado. Esse comentário foi totalmente fora de lugar…",
  "Mas, ao terminar de falar, seus olhos buscaram Adrián com melancolia e resignação.",
  "— Eu voltei sem esperar nada. Enquanto vocês ainda aceitarem minha presença no grupo e eu puder ficar por perto, já fico feliz…",
  "— Para de falar bobagem, mulher. Você sempre vai ser a queridinha do grupo. Ai de quem se atrever a te incomodar! Estamos aqui para te defender. Não é, Adri? —disse Beto, batendo no próprio peito com lealdade exagerada.",
  "Adrián não disse muita coisa.",
  "Apenas segurou a taça de vinho e a girou de leve.",
  "A cena lhe parecia familiar.",
  "Anos antes, ele costumava ser assim.",
  "Gostava de ver os amigos brincando e rindo com Paulina.",
  "Só quando a bagunça saía do controle e todos recorriam a ele, Adrián intervinha para colocar um pouco de ordem.",
  "Agora, vendo que voltavam a buscar sua aprovação, ele sorriu.",
  "— Claro.",
  "Olivia não voltou para casa.",
  "Fez check-in no hotel que havia reservado.",
  "Toda a frustração e toda a dor explodiram no instante em que a porta do quarto se fechou.",
  "A imagem de Beto imitando sua forma de andar aparecia repetidamente diante dos olhos.",
  "As gargalhadas ecoavam nos ouvidos como uma maldição, girando sem parar.",
  "No fundo, Olivia sabia havia muito tempo o que os amigos de Adrián diziam pelas costas.",
  "Nunca tinha contado ao marido.",
  "Eram amigos de infância dele.",
  "Ela entendia.",
  "Ele trabalhava duro fora de casa.",
  "Também entendia.",
  "Por isso, não queria causar problemas.",
  "Não queria incomodá-lo.",
  "Muito menos queria que ele tivesse conflitos com os amigos por culpa dela.",
  "Mas agora percebia o quanto tinha sido ingênua.",
  "Como ele brigaria com os próprios amigos por ela?",
  "Eles eram os amigos de uma vida inteira.",
  "E ela era o quê, em comparação?",
  "Apenas uma dívida que ele se obrigou a pagar levando-a ao altar.",
  "Um peso.",
  "Uma carga.",
  "Sem ela, a vida de Adrián seria muito mais feliz.",
  "“Ela é uma aleijada! Se você não se casasse com ela, quem iria querer?”",
  "“Sendo manca, ainda reclama de se casar com alguém como Adri?”",
  "“Se eu fosse o Adri, preferia ter sido atropelado no lugar dela a casar com uma inválida e virar motivo de piada.”",
  "“Os donos de outras empresas levam esposas elegantes e apresentáveis. Só o nosso Adri não tem ninguém para exibir em público.”",
  "Todos os rumores.",
  "Todos os comentários cruéis que Olivia ouvira durante aqueles cinco anos.",
  "Tudo voltou como uma maré alta, formando um redemoinho enorme que a envolvia e a afogava.",
  "Faltava ar.",
  "Parecia que o coração e os pulmões estavam sendo rasgados.",
  "Com as mãos tremendo, abriu um álbum no celular que não tinha coragem de ver havia cinco anos.",
  "Ali estavam os registros dos ensaios e apresentações da faculdade.",
  "Desde que soube que nunca mais poderia pisar num palco, Olivia trancou todas as fotos e vídeos de dança com senha, prometendo a si mesma que jamais os abriria de novo.",
  "Naquele momento, com a ponta dos dedos trêmula, tocou em um vídeo aleatório.",
  "A música começou.",
  "Na tela, Olivia girava, saltava, fazia um grand jeté no ar.",
  "Aquela Olivia também brilhava.",
  "Tinha um corpo ágil, forte.",
  "Também recebia aplausos ensurdecedores.",
  "Então… tinha sido um erro salvá-lo?",
  "Mas, mesmo no momento em que o salvou, ela nunca pensou em se casar com ele.",
  "Foi Adrián quem disse que queria se casar.",
  "Foi Adrián quem planejou um pedido grandioso.",
  "Foi Adrián quem se ajoelhou diante dela com um enorme anel de diamantes.",
  "Foi ele quem lhe deu esperança.",
  "A mão de Olivia tremeu ao desligar o celular com força.",
  "Pela primeira vez em cinco anos, ela desabou na cama e chorou alto.",
  "Chorou por muito, muito tempo.",
  "Tanto que o próprio corpo ficou exausto.",
  "Tanto que não restaram lágrimas.",
  "Só uma dor queimando como fogo vivo.",
  "Mas foi justamente essa dor que lhe trouxe um pouco de clareza depois daquele redemoinho sufocante.",
  "Quanto mais doía, mais lúcida ela ficava.",
  "Foi ao banheiro e lavou o rosto com água fria, obrigando-se a se acalmar.",
  "Diante do espelho, vendo o próprio reflexo apagado, disse a si mesma em silêncio:",
  "“Olivia, chorar uma vez basta. Você está proibida de chorar de novo. Agora, por favor, jante direito, descanse e amanhã faça uma boa prova.”",
  "A única coisa pela qual era grata era que, durante os longos cinco anos de casamento, para matar o tédio, havia estudado todos os dias.",
  "Não porque tivesse grandes ambições.",
  "Mas porque lhe sobrava tempo demais.",
  "E o vazio era insuportável.",
  "Esperar Adrián voltar para casa era toda a sua vida.",
  "Mas ele sempre chegava muito tarde.",
  "No começo, Olivia pensava que ele estava ocupado com o trabalho.",
  "Mais tarde, entendeu que ele apenas não queria voltar cedo e encará-la.",
  "Ela ouviu isso com os próprios ouvidos.",
  "Naquela época, com pena do quanto ele trabalhava, reuniu coragem para demonstrar carinho.",
  "Preparou pessoalmente uma refeição especial e foi até a empresa para entregá-la.",
  "Mas ouviu uma conversa que não deveria ter ouvido.",
  "Adrián falava com Beto no escritório.",
  "Beto perguntava por que ele ainda não tinha ido embora, já que era tarde demais e quase não havia ninguém na empresa. O que o dono fazia trabalhando até aquela hora?",
  "Adrián respondeu:",
  "— Não sei como voltar e encarar o entusiasmo da Olivia.",
  "Na época, a ingênua Olivia não entendeu completamente o significado da frase.",
  "Mas Beto entendeu.",
  "Ele exclamou, escandalizado:",
  "— Não me diga… Adri, não me diga que vocês ainda não tiveram intimidade, né?",
  "Adrián ficou em silêncio.",
  "Era verdade.",
  "Adrián nunca a tocava.",
  "Olivia havia dado indiretas.",
  "Até tomara a iniciativa, engolindo a vergonha.",
  "Mas, todas as vezes, ele a rejeitava com alguma desculpa.",
  "“Você não está muito bem de saúde.”",
  "“Tenho estado cansado demais esses dias.”",
  "Ela não era boba.",
  "Aos poucos, entendeu que ele não a amava.",
  "Por isso não queria tocá-la.",
  "Mas ouvir aquilo foi como sentir cem facas atravessando o peito.",
  "Doeu tanto que quase não conseguiu respirar.",
  "Depois, Beto perguntou, meio brincando, meio sério:",
  "— Adri, será que você não sente nada quando olha para ela? Digo, apesar de tudo, ela é muito bonita.",
  "A resposta de Adrián se tornou uma espinha enterrada no lugar mais profundo do peito de Olivia.",
  "Uma espinha que, nos anos seguintes, a feriu sem parar.",
  "Toda vez que lembrava, sentia uma dor horrível.",
  "Adrián disse naquele momento:",
  "— Eu tentei. Quis ter uma vida normal com ela, mas quando vejo a perna dela, eu… não consigo.",
  "Então era isso.",
  "Aquela perna cheia de cicatrizes, com os músculos atrofiados por ter salvado a vida dele, era repugnante aos olhos dele.",
  "Matava seu desejo.",
  "No fim, Olivia não bateu na porta do escritório.",
  "A comida feita com tanto amor terminou no lixo da empresa.",
  "Desde então, ela nunca mais voltou à Graph Corporation.",
  "Depois daquele episódio, Olivia retomou os estudos.",
  "Na época, não analisou muito.",
  "Só queria acrescentar alguma esperança secreta à sua vida sem cor.",
  "Ter algo para fazer a impedia de se sentir miserável toda vez que lembrava aquela frase cruel.",
  "Quem imaginaria que aquele refúgio, que pertencia apenas a ela, se tornaria sua salvação?",
  "Ela precisava ir bem na prova.",
  "Precisava sair dali.",
  "Ir embora.",
  "Para longe.",
  "Muito longe.",
  "Quanto mais distância, melhor.",
  "A simples ideia ainda doía até a alma.",
  "Olivia nem sabia se a dor era por Adrián ou por ter desperdiçado cinco anos de vida com a pessoa errada.",
  "Mas isso já não importava.",
  "O importante era que ela não se permitiria afundar de novo naquele sofrimento.",
  "Mesmo que a ferida demorasse a cicatrizar, teria que tomar a iniciativa para salvar a si mesma.",
  "Pediu serviço de quarto: uma refeição leve e roupa íntima descartável.",
  "Ligou para a recepção e programou uma chamada para acordá-la na manhã seguinte.",
  "Então se obrigou a dormir.",
  "Talvez porque não tivesse dormido na noite anterior, dessa vez conseguiu descansar bem.",
  "No dia seguinte, acordou no horário e ligou o celular.",
  "Mensagens entraram em sequência.",
  "O aparelho vibrou sem parar.",
  "Todas vinham da mesma pessoa.",
  "Adrián.",
  "Olivia não leu nenhuma.",
  "Tinha medo de que afetassem sua concentração para a prova.",
  "Tomou café da manhã no hotel.",
  "Com tudo pronto, saiu em direção ao local do exame.",
  "O hotel ficava muito perto, cerca de cinco minutos a pé.",
  "Mal colocou um pé fora do hotel, o celular vibrou em sua mão.",
  "Era Adrián ligando.",
  "Olivia entrou em pânico e quase deixou o aparelho cair.",
  "Deslizou o dedo rapidamente para recusar a chamada e desligou o celular outra vez.",
  "Quando saiu da prova, o coração ainda batia descontrolado.",
  "Mas dessa vez era por alegria.",
  "Ela sentia que tinha ido bem.",
  "O avaliador da parte oral sorrira durante toda a conversa.",
  "Na parte de compreensão auditiva, entendera quase tudo.",
  "As seções de leitura e escrita foram concluídas sem grandes dificuldades.",
  "Não se atrevia a calcular a pontuação.",
  "Mas, pelo menos, havia terminado.",
  "E não tinha sido tão ruim.",
  "Caminhava sozinha pela calçada, cabeça baixa, repassando mentalmente cada detalhe da prova, quando um par de sapatos de couro apareceu em seu campo de visão.",
  "Não esperava que alguém parasse de propósito para bloquear seu caminho.",
  "Não teve tempo de frear e bateu na pessoa.",
  "Se ele não a tivesse segurado, Olivia teria caído.",
  "E aquela pessoa era justamente quem ela menos queria ver.",
  "Adrián.",
  "— Olivia!",
  "Ela percebeu que ele estava furioso.",
  "Mas fazia um esforço visível para reprimir a raiva.",
  "— Por que você não dormiu em casa? —perguntou ele, segurando-a pelos ombros e suavizando a voz.",
  "Soava como sempre.",
  "Calmo.",
  "Gentil.",
  "“Você realmente não sabe por que eu não voltei?”, pensou ela.",
  "Mas não tinha energia para discutir isso agora.",
  "Com o choque, a bolsa dela caiu no chão e se abriu.",
  "A caneta especial usada no exame apareceu pela abertura.",
  "Ela não queria que Adrián soubesse que tinha feito a prova.",
  "Soltou-se do aperto dele num movimento brusco, abaixou-se e empurrou a caneta para o fundo da bolsa o mais rápido possível, antes de fechar o zíper com força.",
  "— O que é isso? —perguntou ele, olhando para a bolsa.",
  "— Uma caneta.",
  "Ela fingiu calma, embora apertasse a alça da bolsa com tanta força que seus dedos ficaram pálidos.",
  "— Deixa eu ver —ordenou.",
  "Não.",
  "Ela não podia deixar.",
  "Abraçou a bolsa com mais força.",
  "— Para que você quer uma caneta?",
  "— Não a caneta. Me dê seu celular —disse ele.",
  "Olivia hesitou por um instante, mas acabou tirando o celular e entregando.",
  "Estava desligado.",
  "Ele apenas olhou e devolveu.",
  "— Liguei inúmeras vezes. Mandei um monte de mensagens. Por que não respondeu? Ainda está brava?",
  "Ela segurou o celular e sentiu um alívio enorme.",
  "Estava apavorada com a possibilidade de ele vasculhar o conteúdo. Se abrisse o e-mail e visse a confirmação do exame, Olivia não saberia o que fazer.",
  "Pensou por um momento.",
  "Na verdade, já não importava.",
  "Ela só queria ir embora.",
  "E esse desejo ficou ainda mais forte ao vê-lo diante de si.",
  "Como ela não respondeu, Adrián presumiu que ainda estivesse fazendo birra e suspirou.",
  "— Você sempre foi tão razoável. Como desta vez nem voltou para dormir em casa por uma bobagem dessas?",
  "Olivia juraria que não queria mais se irritar com aquelas coisas.",
  "Mas aquela frase de Adrián faria até um santo perder a paciência.",
  "— Então o que aconteceu ontem também foi culpa minha? Eu fui a irracional? —não conseguiu se conter— Eu devia ter entrado e parabenizado o Beto? Dito: “Nossa, que imitação incrível, que talento”?",
  "Adrián fez uma expressão desconfortável.",
  "— Não foi isso que eu quis dizer. O que quero dizer é que você não pode controlar o que os outros falam. Não precisa levar as palavras deles tão…",
  "— Eu não controlo os outros, mas você podia ter feito alguma coisa! —Ela o encarou— O que você estava fazendo? Você e sua querida Paulina estavam abraçados, morrendo de rir.",
  "— Olivia! —O rosto dele mudou.",
  "Pela primeira vez, mostrou raiva de verdade.",
  "Olivia entendeu.",
  "Paulina era seu ponto fraco.",
  "Um território intocável.",
  "O que mais havia a dizer?",
  "Abraçou a bolsa, desviou dele e continuou andando.",
  "Mas Adrián estendeu o braço e a segurou pela cintura, impedindo-a de ir embora.",
  "— Desculpa. Eu errei. Não devia ter levantado a voz —disse em tom baixo—. É só que… não quero que você interprete mal a Paulina. Somos apenas amigos, como eu sou com os outros. Eu a vejo como um dos rapazes. Ela não é casada, e se você fala dela desse jeito, pode prejudicá-la.",
  "Olivia não entendia.",
  "Não eram eles que faziam as coisas?",
  "Paulina se apoiava nele com descaramento.",
  "Se faziam, por que tinham medo de que alguém falasse?",
  "Mas ela apenas respondeu com um som seco:",
  "— Ah.",
  "Ele percebeu a indiferença.",
  "— Por que continua tão irritada? Você foi sozinha para um hotel, não voltou para casa e eu nem reclamei de nada. Ainda assim, continua fazendo drama?",
  "Sim.",
  "Claro.",
  "A culpa era toda dela.",
  "— Já chega. Não fique brava. Vamos comer alguma coisa e depois eu te levo para comprar o que quiser. Pode ser?",
  "Olivia pensou.",
  "Tudo bem.",
  "Tinha algo a dizer a ele.",
  "Adrián a levou a um restaurante próximo.",
  "Ao entrar, diante dos olhares dos garçons e por puro hábito, Olivia sentiu vontade de abaixar a cabeça, levantar a gola do casaco e se esconder atrás de Adrián, caminhando devagar para disfarçar a mancada.",
  "Mas relaxou.",
  "Se não estava à altura, então não estava.",
  "De qualquer forma, não pretendia mais ficar ao lado dele.",
  "Eles se sentaram.",
  "Adrián fez o pedido.",
  "Quando os pratos chegaram, ele lhe passou os talheres usando o mesmo tom gentil de sempre.",
  "— Coma. Pedi o que você gosta.",
  "Olivia olhou para a comida.",
  "Tudo tinha pimenta.",
  "Tudo era apimentado.",
  "Ela sorriu com tristeza.",
  "Ele não sabia que ela não podia comer pimenta.",
  "Se em casa sempre cozinhavam pratos apimentados, era porque ele adorava.",
  "— Não estou com fome —disse, sem tocar nos talheres—. Tenho uma coisa para te dizer.",
  "— O que foi? —Ele curvou levemente os lábios—. Quer ir aonde? Eu te acompanho. Hoje tirei o dia livre. À tarde podemos passear e à noite jantamos na casa dos seus pais.",
  "Olivia ficou olhando para aquele sorriso tão discreto, quase imperceptível.",
  "Ao pensar no que estava prestes a dizer, sentiu uma dor aguda.",
  "— Adrián… —A voz falhou, traindo sua fragilidade.",
  "— Hm? Olivia? —Ele segurou a mão dela— O que foi? Quer chorar? Chore. Não segure.",
  "O tom era extremamente suave.",
  "Quase irreal.",
  "Idêntico ao daquela vez, anos atrás, quando ela saiu da cirurgia.",
  "Ele a levou para o quarto com a enfermeira e permaneceu velando seu sono, perguntando com aquela mesma voz doce:",
  "“Olivia, está doendo? Se estiver, chore. Não aguente sozinha…”",
  "Naquele tempo, ela acreditou que aquele cuidado delicado era o melhor analgésico.",
  "Que pena que levou tantos anos para entender que a gentileza de um homem nem sempre vira amor.",
  "— Adrián, vamos nos divorciar —murmurou, retirando a mão enquanto as lágrimas começavam a embaçar sua visão.",
  "Adrián franziu a testa.",
  "Não esperava ouvir aquilo.",
  "Depois de um breve silêncio, pediu um prato limpo ao garçom.",
  "Pegou um pedaço de peixe e, com paciência, retirou os espinhos usando o garfo.",
  "Sem elevar a voz, disse:",
  "— Eu sei que você ainda está chateada, mas falar em divórcio é uma imprudência. Se nos separarmos, o que você vai fazer? Como vai viver sozinha?",
  "A respiração de Olivia se agitou.",
  "Durante cinco anos, aos olhos do mundo, ela havia sido apenas uma parasita.",
  "Sem Adrián, não passava de uma pobre inútil que ninguém desejaria e que não saberia sobreviver.",
  "E ele pensava exatamente a mesma coisa.",
  "— Claro que posso! —Foi a primeira vez que ela o desafiou.",
  "A primeira vez que tentou defender a própria dignidade.",
  "Mas Adrián apenas sorriu, convencido de que era birra.",
  "Colocou o peixe limpo diante dela.",
  "— Coma. Dou permissão para continuar brava por mais um tempo, mas quando terminar de comer, o assunto acaba.",
  "— Eu não estou brava. Eu realmente quero o divórcio! —exclamou ela.",
  "Que palavras precisava usar para que Adrián entendesse que não era capricho?",
  "— Chega.",
  "Ele largou os talheres sobre a mesa.",
  "— Hoje cancelei duas reuniões e um compromisso de negócios só para ficar com você. Não sei se amanhã ou depois terei tempo livre. Vou repetir: Pau é uma grande amiga. É como se fosse um dos rapazes. Eu a trato igual ao Beto e aos outros. Ela gosta de você e quer ser sua amiga, mas com essa atitude… como espera que eu a traga para conviver com você?",
  "— Então não traga.",
  "Olivia não acreditava nem por um segundo que Paulina quisesse ser sua amiga.",
  "— Olivia! —A voz dele revelou irritação.",
  "Ela sabia.",
  "Bastava o assunto tocar em Paulina para a paciência dele evaporar.",
  "— Coma. Quando terminar, vamos ao shopping comprar o que quiser. Depois jantamos com seus pais. Há quanto tempo você não os visita? —disse ele, continuando a servi-la.",
  "Olivia decidiu não se punir.",
  "Pegou os talheres e comeu o necessário.",
  "Acontecesse o que acontecesse, sua prioridade era manter-se saudável.",
  "Não fazia sentido descontar a raiva no próprio estômago.",
  "— Assim eu gosto —a voz de Adrián recuperou a doçura habitual—. E sobre o divórcio, não quero que você volte a mencionar isso.",
  "Olivia parou por um instante.",
  "Depois continuou comendo em silêncio.",
  "Ao terminar, não tinha vontade de fazer compras.",
  "Mas Adrián insistiu e dirigiu até o shopping.",
  "Em cinco anos de casamento, as vezes em que ele a acompanhara para comprar algo podiam ser contadas nos dedos de uma mão.",
  "Na verdade, as aparições públicas dos dois juntos eram igualmente raras.",
  "A iluminação do lugar era intensa demais, quase agressiva, mesmo durante o dia.",
  "Pouco acostumada, Olivia caminhava com cautela, um passo atrás dele, quase em sua sombra, abraçada à bolsa.",
  "O térreo estava cheio de boutiques de bolsas, relógios e joias.",
  "— O que quer comprar? —perguntou ele, virando-se.",
  "Ela não queria nada.",
  "Só queria voltar para casa.",
  "Mas antes que pudesse dizer uma sílaba, alguém gritou de longe:",
  "— Senhor Vargas!",
  "— É um sócio de uma empresa com quem acabamos de fechar negócio. Vou cumprimentá-lo —avisou Adrián—. Vá olhando as lojas. Já te alcanço.",
  "Olivia não conhecia os clientes dele.",
  "Observou Adrián apertar a mão de um homem a certa distância, ficando parada no meio do corredor.",
  "Todo aquele luxo excessivo não despertava interesse algum.",
  "— Senhorita, é sua vez —avisou uma atendente.",
  "Só então Olivia percebeu que, sem querer, havia parado na fila de uma loja de grife.",
  "— Ah, não. Obrigada —desculpou-se e saiu.",
  "Caminhou sem rumo pelos corredores até que viu uma silhueta familiar no balcão de uma relojoaria de prestígio.",
  "Paulina.",
  "Ao reconhecer a marca dos relógios, sentiu um peso no peito.",
  "Seus pés a levaram até o balcão quase contra sua vontade.",
  "Beto estava acompanhando Paulina.",
  "À medida que Olivia se aproximava, a conversa entre os dois ficava mais clara.",
  "— Se gostou, compra —dizia Beto.",
  "— Não sei se devo. É caríssimo —respondeu Paulina—. Embora o Adri tenha me dado o outro cartão para eu gastar o que quiser, fico com vergonha de comprar algo desse preço.",
  "Olivia ficou petrificada.",
  "As pernas pareciam feitas de chumbo.",
  "O coração também.",
  "Outro cartão.",
  "O cartão do marido dela.",
  "— Se ele te deu, é para usar. Quando você já viu Adri dizer uma coisa e fazer outra? Somos como irmãos há anos, você sabe como ele é. Ele te deu de coração —insistiu Beto.",
  "— Você tem razão…",
  "Paulina começou a mexer o pulso, admirando o relógio de vários ângulos.",
  "Olivia também viu.",
  "— Fica bonito, Beto? Eu amo esse modelo. Sou apaixonada por ele desde a faculdade. Adri prometeu me dar um quando nos formássemos, mas depois…",
  "Depois?",
  "Olivia sorriu com tristeza.",
  "“Depois”, Adrián passou a dar exatamente aquele mesmo modelo de relógio a ela em cada aniversário e em cada aniversário de casamento, durante cinco anos.",
  "Ela chegou a pensar que, embora Adrián fosse frio, ao menos lembrava das datas importantes.",
  "Pensava que, embora os presentes não tivessem criatividade, eram valiosos.",
  "No fim, não era falta de atenção.",
  "Nem falta de coração.",
  "Pelo contrário.",
  "Ele colocava coração demais.",
  "O problema era que o coração dele estava ocupado por outra mulher.",
  "— Então considere que Adri está cumprindo a promessa agora. Leva o que quiser. Ele pode pagar tudo —Beto a incentivou.",
  "— Então eu passo? —Os olhos de Paulina brilharam.",
  "Enquanto isso, Adrián terminava de conversar com o sócio.",
  "O homem estava ali para buscar a esposa.",
  "Ao saber que Adrián também estava fazendo compras com a sua, sugeriu cumprimentá-la.",
  "Olivia viu Adrián se aproximar e, tomada pelo pânico, escondeu-se rapidamente atrás de uma coluna.",
  "Paulina, por outro lado, viu Adrián e começou a acenar, gritando:",
  "— Estou aqui! Vem!",
  "Olivia observou do esconderijo enquanto o marido e o sócio caminhavam até Paulina.",
  "Ela se pendurou no braço de Adrián e o balançou com intimidade.",
  "— Quero comprar este relógio. Você deixa?",
  "— Claro.",
  "O olhar de Adrián era pura ternura.",
  "Aquele brilho dava vida ao rosto dele.",
  "Era uma expressão completamente diferente da máscara sem vida que ele usava em casa com Olivia.",
  "— Obrigada, Adri! Vou pagar! —exclamou Paulina, exibindo o cartão adicional.",
  "O sócio, ao ver a cena, sorriu satisfeito.",
  "— O senhor e a senhora Vargas formam um casal encantador. Dá para ver o amor.",
  "Senhor e senhora Vargas?",
  "Tanto Adrián quanto Paulina ficaram paralisados por um instante.",
  "Mas nenhum dos dois se deu ao trabalho de corrigir o mal-entendido.",
  "Olivia observou enquanto Adrián e Paulina, depois de um breve constrangimento, adaptavam-se rapidamente aos novos papéis.",
  "Riam.",
  "Conversavam animadamente com o sócio comercial.",
  "Pareciam feitos um para o outro.",
  "Olivia tirou uma foto discretamente.",
  "Quando se virou para ir embora, sentiu aquela pontada familiar.",
  "Não era uma dor simples.",
  "Era uma angústia persistente, espalhando-se pelo corpo, formando um nó na garganta e ardor nos olhos.",
  "— Olivia!",
  "Ela ouviu alguém chamá-la quando estava prestes a sair do shopping.",
  "Ao virar, viu uma mulher descendo pela escada rolante, acenando com energia para chamar sua atenção.",
  "Era Carmen Ortega.",
  "Sua professora.",
  "Sua antiga mentora na academia de dança.",
  "— Professora! —exclamou Olivia, incapaz de esconder a surpresa e a alegria.",
  "Carmen desceu apressada os últimos degraus, aproximou-se e segurou as duas mãos de Olivia com entusiasmo.",
  "— Achei que era você e não me enganei! —disse a professora com um sorriso radiante— Como você está? Passaram cinco anos sem notícias suas.",
  "Olivia sentiu tristeza.",
  "Cinco anos tinham passado, e sua vida parecia ter ficado parada, convertida numa sombra do que um dia fora.",
  "Com que rosto poderia se apresentar diante da própria mentora?",
  "— Está com pressa? Se não estiver ocupada, podemos procurar um lugar para tomar café e conversar —propôs Carmen, sem soltar sua mão.",
  "Não.",
  "Olivia não tinha pressa.",
  "Se aquilo tivesse acontecido antes, a insegurança a teria feito se trancar de novo, rejeitando qualquer contato com o mundo da dança.",
  "Mas desde que desbloqueara aquele álbum de fotos no celular, era como se uma rachadura tivesse se aberto em seu céu cinzento.",
  "E por essa rachadura, ela precisava deixar a luz entrar.",
  "— Eu adoraria, professora —respondeu Olivia, assentindo.",
  "Sem saber por quê, seus olhos se encheram de lágrimas.",
  "Carmen a guiou pelo braço até uma cafeteria elegante no térreo, perfeita para conversar.",
  "— O que aconteceu com meus colegas? —perguntou Olivia.",
  "Fazia tempo demais que estava desconectada do próprio mundo.",
  "Saíra de todos os grupos de conversa.",
  "Cortara todos os laços.",
  "Carmen a observou com atenção.",
  "— Você realmente quer saber?",
  "A professora conhecia sua situação.",
  "Olivia, que tinha um futuro brilhante, havia renunciado a tudo de repente.",
  "Carmen até viajara para Altabrisa uma vez para visitá-la depois do acidente.",
  "Olivia assentiu com firmeza.",
  "Então Carmen começou a atualizá-la.",
  "Cinco anos eram suficientes para mudar o destino de qualquer pessoa.",
  "Alguns colegas tinham entrado em companhias de dança prestigiadas, tornando-se bailarinos principais.",
  "Outros foram para o exterior, concluíram doutorados.",
  "Alguns ficaram na academia como professores, formando novas gerações.",
  "Todos tinham avançado em suas trajetórias.",
  "Dado passos enormes.",
  "Todos, menos ela.",
  "Mas, a partir daquele dia, as coisas seriam diferentes.",
  "Olivia recuperaria o tempo perdido.",
  "Mesmo que não pudesse mais dançar profissionalmente, encontraria seu lugar em outro caminho.",
  "— Eu… eu também tenho novidades —disse Olivia, sentindo o rosto aquecer de emoção e vergonha por ter decepcionado as expectativas da professora—. Vou estudar no exterior.",
  "— Que maravilha! —Carmen sorriu com a mesma calidez de sempre— Eu sabia. Minhas alunas não se rendem jamais.",
  "Olivia inclinou-se e contou em voz baixa seus planos de pós-graduação fora do país.",
  "— Excelente. Você tem que aproveitar. —Carmen apertou sua mão com carinho— Por coincidência, teremos uma turnê internacional em breve. Você deveria vir conosco para se acostumar com o ambiente e ver como é a vida lá fora.",
  "— Eu… —Olivia hesitou— A senhora acha que posso? Sabe que minha perna não está bem. Não posso dançar e caminho mais devagar que os outros. Meu mestrado será teórico.",
  "— Claro que pode! Se não fosse aquele acidente, você faria parte do elenco principal da Companhia Nacional de Dança. Desta vez, venha como apoio. Pode ajudar na logística, na maquiagem, no que for.",
  "Carmen falava com determinação.",
  "Sem tratá-la como inválida.",
  "Olivia não conseguiu evitar um sorriso.",
  "Gostava daquela sensação.",
  "A sensação de não ser vista com pena.",
  "Não podia mais dançar, era verdade.",
  "Mas ainda podia ser útil.",
  "Não era um objeto velho e inútil.",
  "Naquele momento, o celular de Carmen vibrou sobre a mesa.",
  "— É meu marido. Você se importa se ele se juntar a nós? —perguntou Carmen.",
  "— Claro que não —respondeu Olivia com um sorriso.",
  "No fundo, sentia certo nervosismo.",
  "Depois de cinco anos de isolamento, havia perdido o costume de lidar com desconhecidos.",
  "Mas precisava dar o primeiro passo.",
  "— Vou dizer para ele vir, então —disse Carmen, digitando uma resposta.",
  "O que Olivia jamais imaginou foi que o marido da professora Carmen fosse justamente o novo sócio de Adrián.",
  "O mesmo homem com quem seu marido conversava havia poucos minutos.",
  "— Ele veio a Altabrisa a negócios e aproveitei para acompanhá-lo por alguns dias. Nunca pensei que encontraria você. É o destino…",
  "Enquanto Carmen falava e apresentava o marido à distância, Olivia viu Adrián, Paulina e o esposo da professora caminhando juntos em direção à mesa.",
  "Eles chegaram.",
  "Olivia permaneceu sentada, observando a fascinante mudança de cores nos rostos de Adrián e Paulina.",
  "Do vermelho ao pálido em questão de segundos.",
  "— Venham, sentem-se. Apresento minha esposa, Carmen. Ela é professora de dança —disse o senhor Ortiz, marido de Carmen—. Querida, este é o senhor Adrián, com quem estou fechando negócio. E esta é a esposa dele.",
  "Ao ouvir a palavra “esposa” se referindo a Paulina, a mão de Adrián tremeu.",
  "Paulina parecia querer ser engolida pelo chão.",
  "Não sabia onde se enfiar.",
  "Ambos olharam para Olivia em pânico.",
  "Ela os encarou e sorriu de forma quase imperceptível.",
  "Carmen fez as apresentações.",
  "— Este é meu marido, Ramiro Ortiz —disse, apontando para o homem.",
  "Depois apontou para Olivia.",
  "— E esta é minha aluna, Olivia Muñoz. A aluna com mais chances de ganhar o Prêmio Nacional de Dança da geração dela.",
  "Ao ouvir “Prêmio Nacional de Dança”, o olhar de Adrián se apagou.",
  "Seus olhos desceram por instinto para as pernas de Olivia, escondidas sob a mesa.",
  "Olivia percebeu.",
  "Naquele instante, os olhos dele refletiam uma dor genuína.",
  "E como não doeria?",
  "Se ela não tivesse machucado a perna naquele dia, ele não teria se casado por culpa.",
  "E a mulher ao lado dele agora poderia ser sua esposa diante dos olhos de todos.",
  "Olivia sorriu com ironia.",
  "— Na verdade, eu sou…",
  "— Ai! —Paulina gritou, interrompendo Olivia com um alarido agudo.",
  "Olivia se calou.",
  "Paulina havia derramado a xícara.",
  "O café quente manchou suas mãos e roupas.",
  "— Desculpa… como sou desastrada, mil desculpas —balbuciou Paulina, pegando guardanapos freneticamente para se limpar—. Que vergonha.",
  "— Não se preocupe, não foi nada —disse Carmen, alheia à verdadeira tensão, ajudando-a com mais guardanapos.",
  "Uma xícara de café havia impedido Olivia de dizer a verdade.",
  "Mas se Olivia quisesse continuar, eles realmente conseguiriam impedi-la?",
  "Diante dela, Adrián a encarava em súplica, negando quase imperceptivelmente com a cabeça.",
  "Os lábios dele formaram um “não diga” silencioso e desesperado.",
  "Na verdade, Olivia não pretendia denunciá-los.",
  "Só tinha soltado aquela frase pela metade para saborear o pânico deles.",
  "Aquela reunião se transformou num estudo de contrastes.",
  "Alguns estavam sentados sobre brasas.",
  "Outros permaneciam perfeitamente calmos.",
  "Quando Olivia ergueu a xícara, Carmen percebeu o anel em seu dedo.",
  "— Você está usando aliança. Casou? Quem é seu marido?",
  "A pergunta caiu como uma bomba, fazendo Adrián e Paulina empalidecerem outra vez.",
  "Olivia olhou para a mão de Adrián, apoiada perto da xícara, e sorriu com desprezo.",
  "Ele nunca usava a aliança.",
  "Tinha tirado logo depois do casamento.",
  "Provavelmente estava juntando poeira em alguma gaveta esquecida.",
  "— Sim. Sou casada há cinco anos —respondeu Olivia em tom casual—. Meu marido se chama Vargas.",
  "— Vargas? Que coincidência. Eu também —Adrián se apressou em dizer, com a voz um pouco mais alta que o normal.",
  "A mensagem implícita era clara.",
  "Ele implorava para que ela se calasse.",
  "— Sim. Ele também é Vargas e também trabalha com negócios —disse Olivia, tomando um gole da bebida—, embora, claro, não administre uma empresa tão grande quanto a do senhor Vargas aqui presente.",
  "Através do vapor da xícara, viu os ombros de Adrián relaxarem.",
  "— Que coincidência. Da próxima vez, deveríamos convidar seu marido e tomar algo todos juntos —propôs Ramiro, simpático por consideração à aluna da esposa.",
  "O rosto de Adrián voltou a se tensionar.",
  "Olivia achou hilário.",
  "Em cinco anos de casamento, Adrián não havia mostrado tantas expressões faciais quanto naquela única tarde.",
  "Diante daquela situação, ele não suportou a pressão por muito tempo.",
  "Depois de conversar mais um pouco sobre amenidades, desculpou-se dizendo que tinha assuntos pendentes.",
  "Mas, antes de ir embora, lançou um olhar para Olivia.",
  "Um aviso silencioso.",
  "Ele queria que ela também fosse embora.",
  "Tinha medo de que ela falasse demais se ficasse sozinha com os Ortiz.",
];
