/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeumaridodormiacomminhamelhoramigaRouteImport } from './routes/meumaridodormiacomminhamelhoramiga'
import { Route as MeudesamorperfeitoRouteImport } from './routes/meudesamorperfeito'
import { Route as IndexRouteImport } from './routes/index'

const MeumaridodormiacomminhamelhoramigaRoute =
  MeumaridodormiacomminhamelhoramigaRouteImport.update({
    id: '/meumaridodormiacomminhamelhoramiga',
    path: '/meumaridodormiacomminhamelhoramiga',
    getParentRoute: () => rootRouteImport,
  } as any)
const MeudesamorperfeitoRoute = MeudesamorperfeitoRouteImport.update({
  id: '/meudesamorperfeito',
  path: '/meudesamorperfeito',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meudesamorperfeito': typeof MeudesamorperfeitoRoute
  '/meumaridodormiacomminhamelhoramiga': typeof MeumaridodormiacomminhamelhoramigaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meudesamorperfeito': typeof MeudesamorperfeitoRoute
  '/meumaridodormiacomminhamelhoramiga': typeof MeumaridodormiacomminhamelhoramigaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meudesamorperfeito': typeof MeudesamorperfeitoRoute
  '/meumaridodormiacomminhamelhoramiga': typeof MeumaridodormiacomminhamelhoramigaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meudesamorperfeito' | '/meumaridodormiacomminhamelhoramiga'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meudesamorperfeito' | '/meumaridodormiacomminhamelhoramiga'
  id:
    | '__root__'
    | '/'
    | '/meudesamorperfeito'
    | '/meumaridodormiacomminhamelhoramiga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeudesamorperfeitoRoute: typeof MeudesamorperfeitoRoute
  MeumaridodormiacomminhamelhoramigaRoute: typeof MeumaridodormiacomminhamelhoramigaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meumaridodormiacomminhamelhoramiga': {
      id: '/meumaridodormiacomminhamelhoramiga'
      path: '/meumaridodormiacomminhamelhoramiga'
      fullPath: '/meumaridodormiacomminhamelhoramiga'
      preLoaderRoute: typeof MeumaridodormiacomminhamelhoramigaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meudesamorperfeito': {
      id: '/meudesamorperfeito'
      path: '/meudesamorperfeito'
      fullPath: '/meudesamorperfeito'
      preLoaderRoute: typeof MeudesamorperfeitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeudesamorperfeitoRoute: MeudesamorperfeitoRoute,
  MeumaridodormiacomminhamelhoramigaRoute:
    MeumaridodormiacomminhamelhoramigaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
